In [ ]:
$env:PATH += ";C:\Users\Open user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts"
PS C:\Users\Open user\Desktop\webpage> streamlit run main.py

In [26]:
import pandas as pd

In [27]:
word_meaning= pd.read_csv("500 words - Sheet1.csv", names= ["words"])
word_meaning

                                                 words
0    Time: The indefinite continued progress of exi...
1    Year: The time taken by the Earth to make one ...
2    People: Human beings in general, considered co...
3    Way: A method, style, or manner of doing somet...
4    Day: A period of 24 hours, starting and ending...
..                                                 ...
537  Cobweb: A spider's web, especially an old or d...
538  Coil: A length of something wound or arranged ...
539  Cracker: A thin, crisp biscuit, typically eate...
540  Dinner: The main meal of the day, typically ea...
541  Eggnog: A traditional drink made with milk, eg...

[542 rows x 1 columns]

In [28]:
word_meaning["word"]= [x.split()[0] for x in word_meaning.words]

In [13]:
word_meaning[:5]

                                               words     word
0  Time: The indefinite continued progress of exi...    Time:
1  Year: The time taken by the Earth to make one ...    Year:
2  People: Human beings in general, considered co...  People:
3  Way: A method, style, or manner of doing somet...     Way:
4  Day: A period of 24 hours, starting and ending...     Day:

In [23]:
sentence = "Fight: A violent confrontation between multiple individuals or groups."

# Split the sentence into words
words = sentence.split()

# Join the words starting from the second word
new_sentence = ' '.join(words[1:])

print(new_sentence)

A violent confrontation between multiple individuals or groups.

In [31]:
meaning= []
for x in word_meaning.words:
    words = x.split()
    new_sentence = ' '.join(words[1:])
    
    meaning.append(new_sentence)

In [34]:
word_meaning["meaning"]= meaning
word_meaning

,words,word,meaning
0,Time: The indefinite continued progress of exi...,Time:,The indefinite continued progress of existence...
1,Year: The time taken by the Earth to make one ...,Year:,The time taken by the Earth to make one revolu...
2,"People: Human beings in general, considered co...",People:,"Human beings in general, considered collectively."
3,"Way: A method, style, or manner of doing somet...",Way:,"A method, style, or manner of doing something;..."
4,"Day: A period of 24 hours, starting and ending...",Day:,"A period of 24 hours, starting and ending at m..."
...,...,...,...
537,"Cobweb: A spider's web, especially an old or d...",Cobweb:,"A spider's web, especially an old or dusty one."
538,Coil: A length of something wound or arranged ...,Coil:,A length of something wound or arranged in a s...
539,"Cracker: A thin, crisp biscuit, typically eate...",Cracker:,"A thin, crisp biscuit, typically eaten with ch..."
540,"Dinner: The main meal of the day, typically ea...",Dinner:,"The main meal of the day, typically eaten in t..."
541,"Eggnog: A traditional drink made with milk, eg...",Eggnog:,"A traditional drink made with milk, eggs, suga..."

In [36]:
word_meaning.drop("words", axis= "columns", inplace=True)

In [37]:
word_meaning

         word                                            meaning
0       Time:  The indefinite continued progress of existence...
1       Year:  The time taken by the Earth to make one revolu...
2     People:  Human beings in general, considered collectively.
3        Way:  A method, style, or manner of doing something;...
4        Day:  A period of 24 hours, starting and ending at m...
..        ...                                                ...
537   Cobweb:    A spider's web, especially an old or dusty one.
538     Coil:  A length of something wound or arranged in a s...
539  Cracker:  A thin, crisp biscuit, typically eaten with ch...
540   Dinner:  The main meal of the day, typically eaten in t...
541   Eggnog:  A traditional drink made with milk, eggs, suga...

[542 rows x 2 columns]

In [48]:
word_meaning["words"]= word_meaning["word"].str.replace(":", "")
word_meaning[:5]

      word                                            meaning   words
0    Time:  The indefinite continued progress of existence...    Time
1    Year:  The time taken by the Earth to make one revolu...    Year
2  People:  Human beings in general, considered collectively.  People
3     Way:  A method, style, or manner of doing something;...     Way
4     Day:  A period of 24 hours, starting and ending at m...     Day

In [49]:
word_meaning.drop("word", axis= "columns", inplace=True)

In [52]:
word_meaning= word_meaning[["words", "meaning"]]
word_meaning

       words                                            meaning
0       Time  The indefinite continued progress of existence...
1       Year  The time taken by the Earth to make one revolu...
2     People  Human beings in general, considered collectively.
3        Way  A method, style, or manner of doing something;...
4        Day  A period of 24 hours, starting and ending at m...
..       ...                                                ...
537   Cobweb    A spider's web, especially an old or dusty one.
538     Coil  A length of something wound or arranged in a s...
539  Cracker  A thin, crisp biscuit, typically eaten with ch...
540   Dinner  The main meal of the day, typically eaten in t...
541   Eggnog  A traditional drink made with milk, eggs, suga...

[542 rows x 2 columns]

In [57]:
duplicate= word_meaning[word_meaning.duplicated()]
len(duplicate)

11

In [59]:
word_meaning= word_meaning.drop_duplicates()
word_meaning

       words                                            meaning
0       Time  The indefinite continued progress of existence...
1       Year  The time taken by the Earth to make one revolu...
2     People  Human beings in general, considered collectively.
3        Way  A method, style, or manner of doing something;...
4        Day  A period of 24 hours, starting and ending at m...
..       ...                                                ...
536   Cherry      A small round fruit with a single hard stone.
537   Cobweb    A spider's web, especially an old or dusty one.
538     Coil  A length of something wound or arranged in a s...
539  Cracker  A thin, crisp biscuit, typically eaten with ch...
541   Eggnog  A traditional drink made with milk, eggs, suga...

[531 rows x 2 columns]

In [60]:
len(word_meaning)

531

In [61]:
word_meaning.to_csv("C:/Users/Open user/Documents/531_words.csv")

In [ ]:
df.to_csv('/path/to/directory/my_data.csv', index=False)

In [ ]:
from langchain.prompts import PromptTemplate

prompt_template= """
  Given the following context and a question, generate an answer based on this context only.
  In the answer try to provide as much text as possible from "response" section in the source document.
  If the answer is not found in the context, kindly state "I don't know. Don't try to make up an answer

  CONTEXT: {context}
  QUESTION: {question} """

In [ ]:
prompt = PromptTemplate(
    template= prompt_template,
    input_variables= ["context", "question"]
)

# Troubleshooting streanlit

In [ ]:
#Check Path:
$env:PATH -split ';'

In [ ]:
#Add directory to path
env:Path += ";C:\Users\Open user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\Local-packages\Python39\Scripts"

In [ ]:
#Check Execution Policy
Get-ExecutionPolicy

In [ ]:
#Change Execution Policy
Set-ExecutionPolicy RemoteSigned

In [1]:
import pandas as pd

In [3]:
data= pd.read_csv("Daily words.csv")
data

,English Word,Meaning in English,Meaning in Yoruba,Meaning in Igbo,Meaning in Hausa
0,Ant,Tiny insect that lives in colonies,amugbo,nkịta ọhịa,ƙudanci
1,Apple,"A sweet, red fruit that grows on trees.",àpòrò,àkpụlụ,apple
2,Backpack,Bag carried on your back,àpò ìgbésè,akpa,jaka
3,Backpack,A round object used for playing games.,bóòlù,bọl,ƙwallo
4,Balloon,Inflatable toy filled with air,bọ̀lúùfón,bọlụ ọfukwara,bulo
...,...,...,...,...,...
592,GOD,A superhuman being or spirit worshipped.,NaN,NaN,NaN
593,GOLD,A yellow precious metal.,NaN,NaN,NaN
594,GOOD,To be desired or approved of.,NaN,NaN,NaN
595,GOODBYE,Used to express good wishes when parting.,NaN,NaN,NaN
596,GOVERN,"Conduct the policy, actions, and affairs of a ...",NaN,NaN,NaN

In [ ]:
 Give the meaning of any word supplied in English if it is not requested in other languages.